create table if not exists sensor_readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  temperature double precision not null,
  humidity double precision not null
);

alter table sensor_readings enable row level security;

drop policy if exists "Allow anon select sensor readings" on sensor_readings;
drop policy if exists "Allow anon insert sensor readings" on sensor_readings;

create policy "Allow anon select sensor readings"
on sensor_readings
for select
to anon
using (true);

create policy "Allow anon insert sensor readings"
on sensor_readings
for insert
to anon
with check (
  temperature between -30 and 80
  and humidity between 0 and 100
);
